//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class OduncBilgileri
    {
        public int odunc_ID { get; set; }
        public Nullable<int> kullanici_ID { get; set; }
        public Nullable<int> kitap_ID { get; set; }
        public Nullable<System.DateTime> odunc_VerilisTarihi { get; set; }
        public Nullable<System.DateTime> odunc_SonTarih { get; set; }
        public Nullable<bool> odunc_Durumu { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
