//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminBilgileri
    {
        public int ID { get; set; }
        public string admin_Adi { get; set; }
        public string admin_Soyadi { get; set; }
        public string admin_TC { get; set; }
        public string admin_TelefonNumarasi { get; set; }
        public string admin_KullaniciAdi { get; set; }
        public string admin_KullaniciSifresi { get; set; }
    }
}
