//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevliler
    {
        public int gorevli_ID { get; set; }
        public string gorevli_Adi { get; set; }
        public string gorevli_Soyadi { get; set; }
        public string gorevli_TC { get; set; }
        public string gorevli_TelefonNumarasi { get; set; }
        public string gorevli_KullaniciAdi { get; set; }
        public string gorevli_KullaniciSifresi { get; set; }
    }
}
