//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.OduncBilgileri = new HashSet<OduncBilgileri>();
        }
    
        public int kitap_ID { get; set; }
        public string kitap_Adi { get; set; }
        public string kitap_Yazar { get; set; }
        public string kitap_Turu { get; set; }
        public string kitap_Dili { get; set; }
        public Nullable<int> kitap_SayfaSayisi { get; set; }
        public Nullable<int> kitap_YayinTarihi { get; set; }
        public string kitap_Yayinevi { get; set; }
        public Nullable<int> kitap_KayitTarihi { get; set; }
        public Nullable<int> kitap_StokDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncBilgileri> OduncBilgileri { get; set; }
    }
}
