//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.OduncBilgileri = new HashSet<OduncBilgileri>();
        }
    
        public int kullanici_ID { get; set; }
        public string kullanici_Adi { get; set; }
        public string kullanici_Soyadi { get; set; }
        public string kullanici_TC { get; set; }
        public string kullanici_TelNumarasi { get; set; }
        public string kullanici_cinsiyet { get; set; }
        public Nullable<System.DateTime> kullanici_Dogumtarihi { get; set; }
        public string kullanici_KullaniciAdi { get; set; }
        public string kullanici_Sifresi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncBilgileri> OduncBilgileri { get; set; }
    }
}
